# Generated by Django 4.2.2 on 2023-07-18 01:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("university_name", models.TextField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("grade", models.TextField(blank=True, max_length=100, null=True)),
                ("created_on", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.TextField(max_length=50)),
                ("company_name", models.TextField(max_length=150)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField()),
                (
                    "job_discription",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                ("created_on", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Facts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("happy_clients_count", models.PositiveIntegerField()),
                (
                    "happy_clients_description",
                    models.TextField(blank=True, max_length=250, null=True),
                ),
                ("projects_count", models.PositiveIntegerField()),
                (
                    "projects_description",
                    models.TextField(blank=True, max_length=250, null=True),
                ),
                ("awards_count", models.PositiveIntegerField()),
                (
                    "awards_description",
                    models.TextField(blank=True, max_length=250, null=True),
                ),
                ("years_of_exreiance", models.PositiveIntegerField()),
                (
                    "years_of_exreiance_description",
                    models.TextField(blank=True, max_length=250, null=True),
                ),
                ("created_on", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="HardSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("created_on", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("level", models.CharField(max_length=20)),
                ("created_on", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Personal_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=30)),
                ("phone", models.CharField(max_length=40)),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        validators=[django.core.validators.EmailValidator],
                    ),
                ),
                ("city", models.CharField(max_length=40)),
                ("age", models.PositiveIntegerField()),
                ("degree", models.CharField(max_length=20)),
                ("freelance", models.CharField(max_length=20)),
                (
                    "www",
                    models.URLField(validators=[django.core.validators.URLValidator]),
                ),
                ("short_resume", models.TextField(max_length=250)),
                ("sumary_name", models.CharField(max_length=30)),
                ("sumary_description", models.TextField(max_length=300)),
                ("about", models.TextField(blank=True, max_length=300, null=True)),
                ("created_on", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PortfolioDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=20)),
                ("project_description", models.TextField(max_length=600)),
                (
                    "project_url",
                    models.URLField(validators=[django.core.validators.URLValidator]),
                ),
                ("project_date", models.DateField(blank=True, null=True)),
                (
                    "project_image1",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to="Media"
                    ),
                ),
                (
                    "project_image2",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to="Media"
                    ),
                ),
                (
                    "project_image3",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to="Media"
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_name", models.CharField(max_length=20)),
                ("service_description", models.TextField(max_length=200)),
                ("created_on", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "value",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(100),
                            django.core.validators.MinValueValidator(0),
                        ]
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField()),
                ("link_name", models.CharField(max_length=20)),
                ("link_icon", models.ImageField(blank=True, null=True, upload_to="")),
                ("icon_name", models.CharField(blank=True, max_length=30, null=True)),
                ("created_on", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SoftSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("created_on", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("job_position", models.CharField(max_length=50)),
                ("opinion", models.CharField(max_length=300)),
                (
                    "image",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to="Media"
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
