# Generated by Django 4.2.2 on 2023-07-06 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_contact_experience_hardskill_language_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='HardSkill',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Name',
        ),
        migrations.DeleteModel(
            name='ShortResume',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='SocialLink',
        ),
        migrations.DeleteModel(
            name='SoftSkill',
        ),
        migrations.DeleteModel(
            name='Sumary',
        ),
    ]
