# Generated by Django 4.2.2 on 2023-07-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0006_facts_personal_info_delete_contact_delete_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facts",
            name="years_of_exreiance",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="personal_info",
            name="age",
            field=models.PositiveIntegerField(),
        ),
    ]
