# Generated by Django 4.2.2 on 2023-07-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0007_alter_facts_years_of_exreiance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facts",
            name="projects_description",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="facts",
            name="years_of_exreiance_description",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="sociallink",
            name="link_name",
            field=models.CharField(max_length=40),
        ),
    ]
