# Generated by Django 4.2.2 on 2023-07-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0008_alter_facts_projects_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="grade",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="university_name",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="experience",
            name="company_name",
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name="experience",
            name="job_discribtion",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="job_title",
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name="facts",
            name="awards_description",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="facts",
            name="happy_clients_description",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="facts",
            name="projects_description",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="sociallink",
            name="link_name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="softskill",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
