# Generated by Django 4.2.2 on 2023-07-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0009_alter_education_end_date_alter_education_grade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personal_info",
            name="about",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
