# Generated by Django 4.2.2 on 2023-07-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0012_education_created_on_experience_created_on_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("job_position", models.CharField(max_length=50)),
                ("opinion", models.CharField(max_length=300)),
                ("image", models.ImageField(upload_to="")),
                ("created_on", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
