# Generated by Django 4.2.2 on 2023-07-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0013_testimonial"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="is_current",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="experience",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
