# Generated by Django 4.2.2 on 2023-07-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0015_sociallink_link_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="sociallink",
            name="icon_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
