# Generated by Django 4.2.2 on 2023-07-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0016_sociallink_icon_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="image",
            field=models.ImageField(blank=True, default=None, null=True, upload_to=""),
        ),
    ]
