# Generated by Django 4.2.2 on 2023-07-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0017_alter_testimonial_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="experience",
            old_name="job_discribtion",
            new_name="job_discription",
        ),
        migrations.AlterField(
            model_name="experience",
            name="company_name",
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="image",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="Media"
            ),
        ),
    ]
