# Generated by Django 4.2.2 on 2023-07-18 01:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0021_personal_info_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personal_info",
            name="user",
        ),
    ]
