# Generated by Django 4.2.2 on 2023-07-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0024_userinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Massage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=100)),
                ("massage", models.TextField(max_length=1000)),
            ],
        ),
    ]
