# Generated by Django 4.2.2 on 2023-07-25 21:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0025_massage"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PortfolioDetails",
            new_name="PortfolioProject",
        ),
    ]
