# Generated by Django 4.2.2 on 2023-07-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0027_remove_personal_info_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personal_info",
            name="background_image",
            field=models.ImageField(blank=True, null=True, upload_to="Media"),
        ),
    ]
